### ISSUE TITLE
not working after upgrading to go 1.23.0

### ISSUE THREAD

**Issue by nitzan-entro** [vladopajic/go-test-coverage#101]
![Screenshot 2024-09-04 at 15 35 12](https://github.com/user-attachments/assets/a07bbe88-9efe-493b-8e12-17ca91b78a68)

**Comment by vladopajic** [comment]
hey @nitzan-entro, thanks for reporting 

[v2.10.2](https://github.com/vladopajic/go-test-coverage/releases/tag/v2.10.2) was just released with go version update, please check with this version (or just try again)

**Comment by nitzan-entro** [comment]
thanks a lot! works!
