### ISSUE TITLE
Fail on coverage on new PR code only

### ISSUE THREAD

**Issue by aaronryden** [vladopajic/go-test-coverage#28]
Hello, is there an easy way to configure this great tool to fail on coverage thresholds only on new code added in my PR?

**Comment by vladopajic** [comment]
@aaronryden hey, unfortunately no :/

asserting coverage change on source code diff is planned feature, but it wont be implemented  soon.

**Comment by vladopajic** [comment]
@aaronryden issue was opened to track effort for this feature https://github.com/vladopajic/go-test-coverage/issues/42. i'll close this issue, but feel free to provide any inputs on new issue.
