### ISSUE TITLE
"Could not find file, exit status 1" (v2.8.2)

### ISSUE THREAD

**Issue by joeig** [vladopajic/go-test-coverage#55]
Hi, and thanks for building `go-test-coverage`.

Starting with v2.8.2, I get the following error message ([example](https://github.com/joeig/go-powerdns/actions/runs/7168084065/job/19892527626?pr=68)):

```
failed to generate coverage statistics: could not find file [github.com/joeig/go-powerdns/v3/config.go]: can't find "config.go": go/build: go list github.com/joeig/go-powerdns/v3/: exit status 1
go: github.com/jarcoal/httpmock@v1.3.1: GOPROXY list is not the empty string, but contains no entries
```

The quick fix was to pin v2.8.1. I haven't had a chance to look into why this started happening with v2.8.2, but I wanted to record my finding in case someone else stumbles across this.

Johannes

**Comment by vladopajic** [comment]
thanks for reporting this issue. i'll have a look into this

**Comment by vladopajic** [comment]
adding `local-prefix` ([like this](https://github.com/vladopajic/go-powerdns/blob/82f394cda21a1488e909356958371735718afc50/.github/testcoverage.yml#L3)) seems to fix this issue

**Comment by joeig** [comment]
Thanks, @vladopajic! I'll try it out.

With which version did this become necessary?

**Comment by vladopajic** [comment]
it actually hasn't become necessary. i just figured out that, in this case, the most recent version works if that property is set. still haven't done proper investigation to understand what's happening.

**Comment by joeig** [comment]
Thank you for your help!

**Comment by joeig** [comment]
I cannot reproduce this issue with v2.10.1. Thanks for your help.
