### ISSUE TITLE
Test Coverage fail with Go 1.22

### ISSUE THREAD

**Issue by vijaynallagatla** [vladopajic/go-test-coverage#67]
### Issue:
We are bumping the Go version to 1.22 in our services and we see go test coverage fail with following:
```
go: go.mod requires go >= 1.22 (running go 1.21.4)
```

I noticed changes to bump `go-test-coverage` to 1.22 is already committed and not released yet.

**Comment by vladopajic** [comment]
@vijaynallagatla thanks for remaining me. new release is coming right now.

**Comment by vijaynallagatla** [comment]
> @vijaynallagatla thanks for remaining me. new release is coming right now.

Thank you for such a rapid response! 🙌 Much appreciated.
