### ISSUE TITLE
Would be good to allow customising text of the badge

### ISSUE THREAD

**Issue by gemyago** [vladopajic/go-test-coverage#97]
I have a monorepo like codebase that will have different "subprojects". It would be good to allow customizing the text of the badge so that if multiple badges are included, there will be a way to see which subproject it relates to by using a custom text. I think some  cli argument like `--badge-title` or similar will work.

**Comment by vladopajic** [comment]
hey @gemyago 

are you currently using go-test-coverage on this repository? if so, is this tool sufficient for this use case, except badge title?

---- 
the suggestion seems doable, but right now i am not able to work on it. if i may suggest why don't you include badges in following way:

[general repo badge 1] [general repo badge 2]
subproject_1_title: [test badge] [coverage badge]
subproject_2_title: [test badge] [coverage badge]

also i am curious to know why don't you want to have single coverage as aggregate of entire repository?

**Comment by gemyago** [comment]
Hi @vladopajic,

You've built a great tool. I was previously using a set of scripts to aggregate the coverage and calculate the threshold. I'm also not a big fan to upload my code elsewhere to get the coverage summary, and fail if the threshold is broken. It's quite annoying that golang built-in tooling doesn't have this basic feature. 

I've already integrated it on my [apigen](https://github.com/gemyago/apigen) repo. This is a tool that will generate HTTP API layer from openapi spec. Golang is a first language I plan to support since I'm working the most with it, but I also plan to support few others, and typescript is the next. So combining coverage from different languages/tools will not be practical. My thinking was to just show a different badge per language. Your suggestion to use labels next to the badge will do the work, but altering badge title would be ideal.

BTW: I've followed a slightly different approach on uploading the badge. I think it should only be uploaded when the PR is actually merged, so I added a separate [workflow](https://github.com/gemyago/apigen/blob/main/.github/workflows/push-test-artifacts.yml) and [makefile target](https://github.com/gemyago/apigen/blob/main/Makefile#L149-L161) that is using github API  to upload files. Also, I'm uploading both, the badge and coverage HTML file, and badge URL is pointing on the coverage HTML, so when you click it, you can browse and see what's covered... Example from the apigen repo: [![Golang Coverage](https://raw.githubusercontent.com/gemyago/apigen/test-artifacts/coverage/golang-coverage.svg)](https://htmlpreview.github.io/?https://raw.githubusercontent.com/gemyago/apigen/test-artifacts/coverage/golang-coverage.html)
